version: '3.9'
services:
  web:
    build: .
    container_name: flask_app_postgres
    ports:
      - '5000:5000'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
      POSTGRES_HOST: db
    depends_on:
        - db
    networks:
        - app-network
  db:
    image: 'postgres:16'
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    networks:
      - app-network
volumes:
  postgres_data:
networks:
  app-network:

